# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: compose
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(1968bd26-a8cc-43d9-ba28-e41e6587c830)'
        appName: 'mantisbttest'
        multicontainerConfigFile: '**/docker-compose.yml'