# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: compose
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'AzureConnectionRegistry'
        command: 'buildAndPush'
        Dockerfile: '**/php.Dockerfile'
        tags: 
    - task: Docker@2
      inputs:
        containerRegistry: 'AzureConnectionRegistry'
        command: 'buildAndPush'
        Dockerfile: '**/mysql.Dockerfile'
        tags: 
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(1968bd26-a8cc-43d9-ba28-e41e6587c830)'
        appName: 'mantisbproduction'
        multicontainerConfigFile: '**/docker-compose.yml'